name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to docker hub Registry
        uses: docker/login-action@v1
        with:
          registry: 'https://index.docker.io/v1/'
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            gportal/redfish_exporter:${{ github.sha }}
            gportal/redfish_exporter:latest
